### ISSUE TITLE
Chrome show error although seems to be working. 

### ISSUE THREAD

**Issue by nojaf** [nojaf/fable-minimal-service-worker#1]
Hi @whitetigle, @alfonsogarciacaro and @MangelMaxime.
Sorry to bother you but I'm drowing in webpack madness here.

I'm trying to have two bundles in my webpack config. `module.exports = []`.
fable-loader is working nicely however I always see an error when developing in Chrome.

![image](https://user-images.githubusercontent.com/2621499/50818352-03ce1300-1327-11e9-82a8-a21fde716a90.png)

It has something to do with hot-module reloading however I can't put my finger on it.
When changing `SW.fs`, the browser reloads and updates everything accordingly. But I still always see the error in the dev tools.

Can this problem be solved or should I just let it go? When bundling for production I do not have the problem?

**Comment by MangelMaxime** [comment]
I never used Service Worker yet so not sure if I can help.

Do you have the error message ?

**Comment by nojaf** [comment]
No concrete error message in the console, that is part of problem this is so darn confusing.
It does say the line where is goes wrong, and when looking at the place:
![image](https://user-images.githubusercontent.com/2621499/50819421-51984a80-132a-11e9-8600-b7e103f368b0.png)

`webpackHotUpdate` is undefined in the worker.

**Comment by MangelMaxime** [comment]
Is hot update supported in Service Worker by webpack ?

**Comment by nojaf** [comment]
Can't find a clear answer in the documentation. So maybe 🙃

**Comment by nojaf** [comment]
I posted an issue on the webpack repo as I have the exact same problem without any Fable involved.
https://github.com/webpack/webpack/issues/8600

**Comment by alfonsogarciacaro** [comment]
Yes, I have issues with service workers when developing using HMR as well, that's why I only activate the SW in production (see [this](https://github.com/fable-compiler/repl/blob/e9330537855a1b1d73b5dc1bd03f28b97e524f10/src/App/Loader.fs#L93-L95) and [this](https://github.com/fable-compiler/repl/blob/e9330537855a1b1d73b5dc1bd03f28b97e524f10/webpack.config.js#L115-L129)). It's more convenient but you can only test the SW in production 🤷‍♂️

BTW, Service Workers look simple at first, but there are many [edge cases](https://developers.google.com/web/fundamentals/codelabs/your-first-pwapp/#beware_of_the_edge_cases) so atm I only recommend using the [Workbox webpack plugin](https://developers.google.com/web/tools/workbox/guides/codelabs/webpack) (the links above show how the Fable REPL does it).

**Comment by nojaf** [comment]
I actually don't use Service worker for caching so all these webpack plugins are not really what I'm looking for. I use it to send push notifications, so I have custom code in my SW.

This seems possible with `workboxPlugin`, 
```
new workboxPlugin.InjectManifest({
  swSrc: './src/sw.js',
  swDest: 'sw.js'
})
```

However I can't write that code in F# at first glance. Again, maybe I'm asking too much.
The advice only to test SW in production does seem valuable. I could implement some functionally to test my code when logged in as admin. That way it is fairly safe to test in production.

**Comment by whitetigle** [comment]
> Yes, I have issues with service workers when developing using HMR as well, that's why I only activate the SW in production (see this and this). It's more convenient but you can only test the SW in production 

Same here. SW in prod. 

For information, I also do have several bugs with SW in chrome and I haven't yet taken the time to find what's happening. In a weird fashion, on Firefox everything's seems to be working fine. So there are things to check here. One more thing on my TODO.

**Comment by nojaf** [comment]
Thanks all for your feedback!

**Comment by alfonsogarciacaro** [comment]
And Safari doesn't update pages with SW correctly (it doesn't update the Fable REPL unless I do a hard reload for example) 😕 As with any new technology, it seems there're still differences in how browsers deal with SWs.
